---
title: "Tutorial 2: Basic network analysis in R"
author: "Bjarne van der Mark"
output:
  html_document:
    number_sections: false
---

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide', message=FALSE}
library(knitr)
library(igraph)
library(dplyr)
library(reshape2)
library(tidyverse)
library(network)

knitr::opts_chunk$set(
  echo = TRUE,
  tidy.opts = list(width.cutoff = 100),
  tidy = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  cache = TRUE,
  class.source = c("test"),
  class.output = c("test2")
)

options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {
  sprintf("<span style='color: %s;'>%s</span>", color, x)
}
```

```{r klippy, echo=FALSE, include=TRUE}
# klippy::klippy(position = c('top', 'right'))
# klippy::klippy(color = 'darkred')
# klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

On this page you will find my code from tutorial 2.

```{r}
library(igraph)
z <- make_graph("Zachary")
z

plot(z)

is_directed(z)
```

## 2.1
### 2.1.1

```{r}
vcount(z)
ecount(z)
```

### 2.1.2

```{r}
edge_density(z)
```

Question: How would you calculate density using ecount() and vcount()?

Answer: density <- ecount / (vcount * (vcount - 1) / 2)

```{r}
z$density <- edge_density(z)
z
```

### 2.1.3

```{r}
count_components(z)
```

### 2.1.4

```{r}
diameter(z)

mean_distance(z)
```

### 2.1.5

```{r}
transitivity(z, type = "average")
```

## 2.1
### 2.2.1

```{r}
degree(z)

summary(degree(z))

hist(degree(z))

V(z)$degree <- degree(z)

plot(z, vertex.size = V(z)$degree+8, margin= -0.1)

degree(z, v = 3)

```

### 2.2.2

```{r}
betweenness(z)

z <- z %>% 
  set_vertex_attr(
    name = "betweenness",
    value = betweenness(z)
  )
```

###

```{r}
V(z)$closeness <- closeness(z)
```

